version: '3.7'

services:
  postgres:
    environment:
      - POSTGRES_PASSWORD=postgres_pw
      - POSTGRES_USER=postgres_user
      - POSTGRES_DB=default-db
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"
